name: Hello World After PR Merge

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  say-hello:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World! A PR was merged into main 🚀"

      - name: Print today's date
        run: date
